global:
  postgresql:
    auth:
      username: user
      password: userpass123
      database: userdb

primary:
  persistence:
    enabled: true
    size: 2Gi
    storageClass: microk8s-hostpath

service:
  type: ClusterIP
  port: 5432
