config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/nicolasdemol/belovr-cluster.git
      targetRevision: main

applications:
  - name: user-postgres
    namespace: belovr-db
    tool:
      helm:
        releaseName: user-postgres
  - name: chat-postgres
    namespace: belovr-db
    tool:
      helm:
        releaseName: chat-postgres
  - name: content-postgres
    namespace: belovr-db
    tool:
      helm:
        releaseName: content-postgres
