config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/nicolasdemol/belovr-cluster.git
      targetRevision: main

applications:
  - name: user-postgres
    namespace: belovr-db
    path: databases/user-postgres
    tool:
      helm:
        releaseName: user-postgres
        valueFiles:
          - values.yaml
  - name: chat-postgres
    namespace: belovr-db
    path: databases/chat-postgres
    tool:
      helm:
        releaseName: chat-postgres
        valueFiles:
          - values.yaml
  - name: content-postgres
    namespace: belovr-db
    path: databases/content-postgres
    tool:
      helm:
        releaseName: content-postgres
        valueFiles:
          - values.yaml
  - name: redis
    namespace: belovr-infra
    path: infra/redis
    tool:
      helm:
        releaseName: redis
        valueFiles:
          - values.yaml
