apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: belovr-unified-ingress
  namespace: belovr
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # Astuce pour gérer plusieurs domaines externes (cdn et images)
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ssl_server_name on;
      if ($request_uri ~* "^/video/(.*)") {
          proxy_set_header Host cdn.belovr.com;
      }
      if ($request_uri ~* "^/images/(.*)") {
          proxy_set_header Host images.belovr.com;
      }
spec:
  tls:
    - hosts:
        - dev.192.168.1.12.nip.io
      secretName: argocd-ingress-http # On réutilise ton secret existant
  rules:
    - host: dev.192.168.1.12.nip.io
      http:
        paths:
          - path: /video
            pathType: Prefix
            backend:
              service:
                name: proxy-cdn-belovr
                port:
                  number: 443
          - path: /images
            pathType: Prefix
            backend:
              service:
                name: proxy-images-belovr
                port:
                  number: 443
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
