apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: belovr-unified-ingress
  namespace: belovr
  annotations:
    kubernetes.io/ingress.class: nginx
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    # FORCE L'ÉTAT VERT DANS ARGOCD
    argocd.argoproj.io/healthstatus: "Healthy"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # On définit le défaut sur HTTP (pour ton Next.js)
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_ssl_server_name on;
      # On force le HTTPS uniquement pour les chemins Cloudflare
      if ($request_uri ~* "^/video") {
          set $proxy_upstream_protocol https;
          proxy_set_header Host cdn.belovr.com;
      }
      if ($request_uri ~* "^/images") {
          set $proxy_upstream_protocol https;
          proxy_set_header Host images.belovr.com;
      }
spec:
  tls:
    - hosts:
        - dev.192.168.1.12.nip.io
      secretName: argocd-ingress-http
  rules:
    - host: dev.192.168.1.12.nip.io
      http:
        paths:
          - path: /video
            pathType: Prefix
            backend:
              service:
                name: proxy-cdn-belovr
                port:
                  number: 443
          - path: /images
            pathType: Prefix
            backend:
              service:
                name: proxy-images-belovr
                port:
                  number: 443
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
