architecture: standalone

auth:
  enabled: false

master:
  resourcesPreset: "nano"
  persistence:
    enabled: true
    storageClass: microk8s-hostpath
    size: 1Gi

## Disable sentinels and replicas (simplify setup)
replica:
  replicaCount: 0

sentinel:
  enabled: false

## Disable metrics exporter to reduce footprint
metrics:
  enabled: false

## Network policy for local dev (accept all)
networkPolicy:
  enabled: true
  allowExternal: true
